### ISSUE TITLE
Font icons not rendering properly

### ISSUE THREAD

**Issue by flibbertigibbet** [azavea/pfb-network-connectivity#362] opened 2017-04-27 17:33 UTC
Specifically visible on the comparison page removal button at the top of each column, which should display as `icon-cross`, but displays no icon and only became visible after adding the `btn btn-secondary` classes to the parent anchor.

See #347

**Comment by CloudNiner** [comment] 2017-05-10 15:02
Caused by #413 , closing this one

**Closed by CloudNiner** 2017-05-10 15:02 UTC
