### ISSUE TITLE
Potential issue with setup file when running jobs locally

### ISSUE THREAD

**Issue by jcahail** [azavea/pfb-network-connectivity#582] opened 2018-07-30 13:56 UTC
Per Rebecca: "I've tried running the code per the instructions on both a Mac and a PC and I'm encountering an error when running the setup file (/scripts/setup)." 

Traceback: 
PeopleForBikess-MacBook-Air:pfb-network-connectivity PeopleForBikes$ cp deployment/ansible/group_vars/all.example deployment/ansible/group_vars/all

PeopleForBikess-MacBook-Air:pfb-network-connectivity PeopleForBikes$ ./scripts/setup

~/pfb-network-connectivity ~/pfb-network-connectivity/scripts

Bringing machine 'default' up with 'virtualbox' provider...

==> default: Box 'ubuntu/trusty64' could not be found. Attempting to find and install...

    default: Box Provider: virtualbox

    default: Box Version: >= 0

==> default: Loading metadata for box 'ubuntu/trusty64'

    default: URL: https://vagrantcloud.com/ubuntu/trusty64

==> default: Adding box 'ubuntu/trusty64' (v20180709.0.10) for provider: virtualbox

    default: Downloading: https://vagrantcloud.com/ubuntu/boxes/trusty64/versions/20180709.0.10/providers/virtualbox.box

    default: Download redirected to host: cloud-images.ubuntu.com

==> default: Successfully added box 'ubuntu/trusty64' (v20180709.0.10) for 'virtualbox'!

==> default: Importing base box 'ubuntu/trusty64'...

==> default: Matching MAC address for NAT networking...

==> default: Checking if box 'ubuntu/trusty64' is up to date...

==> default: Setting the name of the VM: pfb-network-connectivity_default_1532729135923_83064

==> default: Clearing any previously set forwarded ports...

Vagrant is currently configured to create VirtualBox synced folders with

the `SharedFoldersEnableSymlinksCreate` option enabled. If the Vagrant

guest is not trusted, you may want to disable this option. For more

information on this option, please refer to the VirtualBox manual:

  https://www.virtualbox.org/manual/ch04.html#sharedfolders

This option can be disabled globally with an environment variable:

  VAGRANT_DISABLE_VBOXSYMLINKCREATE=1

or on a per folder basis within the Vagrantfile:

  config.vm.synced_folder '/host/path', '/guest/path', SharedFoldersEnableSymlinksCreate: false

==> default: Clearing any previously set network interfaces...

==> default: Preparing network interfaces based on configuration...

    default: Adapter 1: nat

    default: Adapter 2: hostonly

==> default: Forwarding ports...

    default: 9200 (guest) => 9200 (host) (adapter 1)

    default: 9202 (guest) => 9202 (host) (adapter 1)

    default: 9203 (guest) => 9203 (host) (adapter 1)

    default: 5432 (guest) => 9214 (host) (adapter 1)

    default: 9301 (guest) => 9301 (host) (adapter 1)

    default: 9302 (guest) => 9302 (host) (adapter 1)

    default: 22 (guest) => 2222 (host) (adapter 1)

==> default: Running 'pre-boot' VM customizations...

==> default: Booting VM...

==> default: Waiting for machine to boot. This may take a few minutes...

    default: SSH address: 127.0.0.1:2222

    default: SSH username: vagrant

    default: SSH auth method: private key

    default: Warning: Remote connection disconnect. Retrying...

    default: 

    default: Vagrant insecure key detected. Vagrant will automatically replace

    default: this with a newly generated keypair for better security.

    default: 

    default: Inserting generated public key within guest...

    default: Removing insecure key from the guest if it's present...

    default: Key inserted! Disconnecting and reconnecting using new SSH key...

==> default: Machine booted and ready!

==> default: Checking for guest additions in VM...

    default: The guest additions on this VM do not match the installed version of

    default: VirtualBox! In most cases this is fine, but in rare cases it can

    default: prevent things such as shared folders from working properly. If you see

    default: shared folder errors, please make sure the guest additions within the

    default: virtual machine match the version of VirtualBox you have installed on

    default: your host and reload your VM.

    default: 

    default: Guest Additions Version: 4.3.36

    default: VirtualBox Version: 5.2

==> default: Setting hostname...

==> default: Configuring and enabling network interfaces...

==> default: Exporting NFS shared folders...

==> default: Preparing to edit /etc/exports. Administrator privileges will be required...

Password:

The nfsd service does not appear to be running.

Starting the nfsd service

==> default: Mounting NFS shared folders...

==> default: Mounting shared folders...

    default: /home/vagrant/.aws => /Users/PeopleForBikes/.aws

==> default: Running provisioner: shell...

    default: Running: /var/folders/zg/2rlh79094cg0xhlpt_rzzfw40000gn/T/vagrant-shell20180727-16262-1mpx94z.sh

==> default: Running provisioner: shell...

    default: Running: inline script

    default: /tmp/vagrant-shell: line 1: pip: command not found

The SSH command responded with a non-zero exit status. Vagrant

assumes that this means the command failed. The output for this command

should be in the log above. Please read the output to determine what

went wrong.

**Comment by CloudNiner** [comment] 2018-08-06 12:06
@jcahail can you contact Rebecca and have her do the following:

1. Run `vagrant destroy` to clean up the environment
1. Follow the setup instructions from the beginning
1. Let us know if there's further issues.

It would also be good to suggest that she create an account on GitHub so we can add her as a repository collaborator and interface directly here.

**Comment by CloudNiner** [comment] 2018-08-06 15:35
👍 added as a read only collaborator

**Comment by beckymasond** [comment] 2018-08-08 17:52
I'm running into a different error at the same stage in the instructions, the setup file. This is the same error I ran into the first time I tried to run the analysis locally. 

**First I receive this message:** 
==> default: Setting hostname...
==> default: Configuring and enabling network interfaces...
==> default: Mounting shared folders...
    default: /vagrant => C:/Users/rebec/Documents/pfb-network-connectivity
Vagrant was unable to mount VirtualBox shared folders. This is usually
because the filesystem "vboxsf" is not available. This filesystem is
made available via the VirtualBox Guest Additions and kernel module.
Please verify that these guest additions are properly installed in the
guest. This is not a bug in Vagrant and is usually caused by a faulty
Vagrant box. For context, the command attempted was:

mount -t vboxsf -o vers=3,udp,uid=1000,gid=1000 vagrant /vagrant

The error output from the command was:

unknown mount option `vers=3'

**Then I installed the vagrant-vbguest plugin, ran the setup script again, and received this message:**
==> default: Running provisioner: ansible_local...
`playbook` does not exist on the guest: /vagrant/deployment/ansible/pfb.yml

**Comment by CloudNiner** [comment] 2018-08-08 20:05
Now that the vbguest plugin is installed, could you run `vagrant destroy && ./scripts/setup`, and then if you have issues, post the entire output from `./scripts/setup`?

Could you also post:
- OS version
- Vagrant version (run `vagrant --version` in a terminal)
- Installed vagrant plugins (run `vagrant plugin list` in a terminal)

Unfortunately, I haven't seen either of those error messages before, I was just able to successfully provision with the following:
- MacOS 10.13.6
- Vagrant 2.1.1
- Plugins installed:
  - vagrant-hostmanager (1.8.9)
  - vagrant-vbguest (0.15.2)

**Comment by beckymasond** [comment] 2018-08-09 16:46
I tried running it again on a Mac and progressed farther than on a PC, though the setup script keeps getting hung in various places. I'll keep trying and let you know if I can get it to work. For reference, I'm now using:

* MacOS 10.11.6
* Vagrant 2.1.2
* Plugins installed:
 * vagrant-hostmanager (1.8.9)
 * vagrant-vbguest (0.15.2)

**Comment by CloudNiner** [comment] 2018-08-09 17:05
Ah. If your first set of output in https://github.com/azavea/pfb-network-connectivity/issues/582#issuecomment-411494548 is on Windows, and it looks like it is from the use of `C:/`, you'll need to apply an environment variable before starting the vagrant machine because Windows doesn't NFS support. See (3) under [Notes for Windows Users](https://github.com/azavea/pfb-network-connectivity#notes-for-windows-users) in the README. If you set the environment variable in whatever shell you're using, you should be able to proceed on Windows.

Also, assuming that `MacOS 10.11.6` isn't a typo, that's an older version of the OS, and I'm not sure we have any of those on hand to test on. Could you post any error messages you're seeing on MacOS?

**Comment by CloudNiner** [comment] 2018-08-09 17:10
If it is in fact an older Mac that you're using, the PFB VM requests [4GB of memory](https://github.com/azavea/pfb-network-connectivity/blob/develop/Vagrantfile#L71). If the Mac you're using only has that much system memory, you could see inconsistent issues with provisioning as your computer runs out of memory. It's at least worth checking, especially if the errors are inconsistent from build to build.

**Comment by beckymasond** [comment] 2018-08-13 16:36
I think you're right about the memory issues on the Mac. I'll try to run it on a newer Mac later today or tomorrow. I've attached the terminal output in any case. It stopped progressing at this point. 
[bna_mac.txt](https://github.com/azavea/pfb-network-connectivity/files/2283814/bna_mac.txt)

As for the PC, I am running:
* Microsoft Windows [Version 10.0.17134.165]
* Vagrant 2.1.2
* Plugins installed:
   * vagrant-hostmanager (1.8.9)
   * vagrant-vbguest (0.15.2)
I set the environment variable (correctly this time, I think), and encountered a different error. Error message attached.
[bna_pc.txt](https://github.com/azavea/pfb-network-connectivity/files/2283854/bna_pc.txt)

**Comment by beckymasond** [comment] 2018-08-16 15:48
I ran this on a new Mac and ran into a similar error message to the one on the PC. Attached below.

*Mac OS 10.13.6
*Vagrant 2.0.4
*Plugins installed:
   *vagrant-hostmanager (1.8.9)
   *vagrant-vbguest (0.15.2)

[bna_mac_new.txt](https://github.com/azavea/pfb-network-connectivity/files/2294265/bna_mac_new.txt)

**Comment by CloudNiner** [comment] 2018-08-17 13:58
Are you sure you're running the latest code on the `develop` branch? That's an error that should have been fixed by https://github.com/azavea/pfb-network-connectivity/pull/581/commits/6ec184f447088e7162277760a58a6e53d38d1031

To check this, run `git rev-parse --short HEAD` within the repository on your machine. That should output `fa1e1c3`.

If it doesn't, do the following:
```
git checkout develop
git pull
vagrant destroy
./scripts/setup
```

You'll want to check this on both your MacOS and Windows machines.

**Comment by beckymasond** [comment] 2018-08-21 17:48
I may not have been on the right branch previously...I just tried it again on a PC and the line you specified above does output `fa1e1c3`. The error message I now receive is: 

    default: Running ansible-galaxy...
cd /vagrant && ansible-galaxy install --role-file='/vagrant/deployment/ansible/                                         roles.yml' --roles-path='/vagrant/deployment/ansible/roles' --force
/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/primitives/constant_                                         time.py:26: CryptographyDeprecationWarning: Support for your Python version is                                          deprecated. The next version of cryptography will remove support. Please upgrad                                         e to a 2.7.x release that supports hmac.compare_digest as soon as possible.
  utils.DeprecatedIn23,
- downloading role 'aws-cli', owned by azavea
- downloading role from https://github.com/azavea/ansible-aws-cli/archive/0.1.0                                         .tar.gz
- extracting azavea.aws-cli to /vagrant/deployment/ansible/roles/azavea.aws-cli
 [WARNING]: - azavea.aws-cli was NOT installed successfully: Could not update
files in /vagrant/deployment/ansible/roles/azavea.aws-cli: [Errno 71] Protocol
error
ERROR! - you can use --ignore-errors to skip failed roles and finish processing                                          the list.
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

**Comment by CloudNiner** [comment] 2018-08-21 18:40
Ok, so we're back to where we were originally on PC. While I can't test this myself because I don't have a windows machine, my best guess is that this step in the process is attempting to create symbolic links and that's not possible by default for regular users on Windows. You can try closing your terminal on Windows (git bash/cygwin/etc) and re-starting it as an Administrator, then re-provisioning. If that still fails, there would be additional steps necessary to enable symlinks for a normal user that would be outside the scope of what we'd want people interested in running the BNA to configure. Alternatively, we may be able to modify the provisioning step, but that's additional effort outside the scope of this task.

@spencerrecneps have you seen the above error on Windows, and have any suggestions?

Were your MacOS issues resolved by the above instructions?

**Comment by beckymasond** [comment] 2018-08-21 18:54
Thanks, I'll test on the Mac tomorrow morning and let you know, and I'll try the fix you described for a PC.

**Comment by beckymasond** [comment] 2018-08-22 23:05
Success! On both the Mac and the PC. Thank you for your help troubleshooting.

**Comment by CloudNiner** [comment] 2018-08-23 11:03
That's great news. I'll add a note to the Windows instructions in the README, and we'll call this closed for now.

**Closed by CloudNiner** 2018-08-23 11:03 UTC
Labels: Bug - Medium Priority, in review
